<div class="col-xs-24" style="font-size:10pt;">
	<div class="row">
		<div class="col-xs-24 payout">Payout Structure</div>
		<div class="col-xs-24">
			<div class="col-xs-12">
				{#payout}
					<div class="row">
						<div class="col-xs-12 position">{displayPosition}</div>
						<div class="col-xs-12 amount">{formattedPayoutAmount}</div>
					</div>
				{/payout}
			</div>
		</div>
	</div>
</div>
