<div class="col-xs-24" style="font-size:10pt;">
	<div id="textboxctrl" style="margin-left:10px;margin-bottom:25px;"></div>
	<div id="dropdownctrl" style="margin-left:10px;margin-bottom:25px;"></div>	
	<div id="radiogroupctrl" style="margin-left:10px;margin-bottom:25px;"></div>	
	<div id="checkboxctrl" style="margin-left:10px;margin-bottom:25px;"></div>	
	<div id="togglectrl" style="margin-left:10px;margin-bottom:25px;"></div>	
	<div id="tooltipctrl" style="margin-left:10px;margin-bottom:25px;background-image:url(assets/images/mlb/yankees.png);height:100px;width:100px;cursor:help;""></div>	
	<div id="buttonctrl" style="margin-left:10px;margin-bottom:25px;"></div>	
</div>
