CREATE TABLE `stats`.`mlb_batting` (
  `id` INT AUTO_INCREMENT NOT NULL,
  `athlete_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  `start_date` TIMESTAMP NOT NULL,
  `at_bats` INT NOT NULL DEFAULT 0,
  `ballsHit_flyballs` INT NOT NULL DEFAULT 0,
  `ballsHit_groundballs` INT NOT NULL DEFAULT 0,
  `ballsHit_lineDrives` INT NOT NULL DEFAULT 0,
  `groundIntoDoublePlays_opportunities` INT NOT NULL DEFAULT 0,
  `groundIntoDoublePlays_total` INT NOT NULL DEFAULT 0,
  `hitByPitch` INT NOT NULL DEFAULT 0,
  `hits_doubles` INT NOT NULL DEFAULT 0,
  `hits_extraBaseHits` INT NOT NULL DEFAULT 0,
  `hits_homeRuns` INT NOT NULL DEFAULT 0,
  `hits_singles` INT NOT NULL DEFAULT 0,
  `hits_total` INT NOT NULL DEFAULT 0,
  `hits_triples` INT NOT NULL DEFAULT 0,
  `onBasePercentage` DECIMAL(3,3) NOT NULL DEFAULT 0.0,
  `sluggingPercentage` DECIMAL(3,3) NOT NULL DEFAULT 0.0,
  `onBasePlusSluggingPercentage` DECIMAL(3,3) NOT NULL DEFAULT 0.0,
  `pitchesSeen_ratePerPlateAppearance` DECIMAL(3,3) NOT NULL DEFAULT 0.0,
  `pitchesSeen_total` INT NOT NULL DEFAULT 0,
  `plateAppearances` INT NOT NULL DEFAULT 0,
  `runsBattedIn_gameWinning` INT NOT NULL DEFAULT 0,
  `runsBattedIn_total` INT NOT NULL DEFAULT 0,
  `runsScored` INT NOT NULL DEFAULT 0,
  `sacrifices_hits` INT NOT NULL DEFAULT 0,
  `sacrifices_flies` INT NOT NULL DEFAULT 0,
  `stolenBases_attempts` INT NOT NULL DEFAULT 0,
  `stolenBases_caughtStealing` INT NOT NULL DEFAULT 0,
  `stolenBases_total` INT NOT NULL DEFAULT 0,
  `strikeouts` INT NOT NULL DEFAULT 0,
  `timesOnBase` INT NOT NULL DEFAULT 0,
  `totalBases` INT NOT NULL DEFAULT 0,
  `walks_intentional` INT NOT NULL DEFAULT 0,
  `walks_total` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`));

CREATE TABLE `stats`.`mlb_fielding` (
  `id` INT AUTO_INCREMENT NOT NULL,
  `athlete_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  `start_date` TIMESTAMP NOT NULL,
  `assists` INT NOT NULL DEFAULT 0,
  `ballsHitInZone` INT NOT NULL DEFAULT 0,
  `doublePlays` INT NOT NULL DEFAULT 0,
  `errors` INT NOT NULL DEFAULT 0,
  `fieldingOuts` INT NOT NULL DEFAULT 0,
  `hitsAllowed` INT NOT NULL DEFAULT 0,
  `innings` DECIMAL(3,3) NOT NULL DEFAULT 0.0,
  `opportunities` INT NOT NULL DEFAULT 0,
  `putouts` INT NOT NULL DEFAULT 0,
  `triplePlays` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`));

  CREATE TABLE `stats`.`mlb_pitching` (
    `id` INT AUTO_INCREMENT NOT NULL,
    `athlete_id` INT NOT NULL,
    `event_id` INT NOT NULL,
    `start_date` TIMESTAMP NOT NULL,
    `balks` INT NOT NULL DEFAULT 0,
    `ballsHitAllowed_flyballs` INT NOT NULL DEFAULT 0,
    `ballsHitAllowed_groundballs` INT NOT NULL DEFAULT 0,
    `ballsHitAllowed_lineDrives` INT NOT NULL DEFAULT 0,
    `baserunnersAllowed_ratePerNineInnings` DECIMAL(3,3) NOT NULL DEFAULT 0.0,
    `baserunnersAllowed_total` INT NOT NULL DEFAULT 0,
    `earnedRunAverage` DECIMAL(3,3) NOT NULL DEFAULT 0.0,
    `games_complete` INT NOT NULL DEFAULT 0,
    `games_qualityStarts` INT NOT NULL DEFAULT 0,
    `games_shutouts` INT NOT NULL DEFAULT 0,
    `games_starts` INT NOT NULL DEFAULT 0,
    `games_total` INT NOT NULL DEFAULT 0,
    `groundIntoDoublePlays_percentage` DECIMAL(3,3) NOT NULL DEFAULT 0.0,
    `groundIntoDoublePlays_ratePerNineInnings` DECIMAL(3,3) NOT NULL DEFAULT 0.0,
    `groundIntoDoublePlays_total` INT NOT NULL DEFAULT 0,
    `hitBatsmen` INT NOT NULL DEFAULT 0,
    `hitsAllowed_doubles` INT NOT NULL DEFAULT 0,
    `hitsAllowed_homeRuns_total` INT NOT NULL DEFAULT 0,
    `hitsAllowed_homeRuns_ratePerNineInnings` DECIMAL(3,3) NOT NULL DEFAULT 0.0,
    `hitsAllowed_ratePerNineInnings` DECIMAL(3,3) NOT NULL DEFAULT 0.0,
    `hitsAllowed_total` INT NOT NULL DEFAULT 0,
    `hitsAllowed_triples` INT NOT NULL DEFAULT 0,
    `wildPitches` INT NOT NULL DEFAULT 0,
    `totalBattersFaced` INT NOT NULL DEFAULT 0,
    `walks_intentional` INT NOT NULL DEFAULT 0,
    `walks_total` INT NOT NULL DEFAULT 0,
    `walksPlusHits_ratePerInning` DECIMAL(3,3) NOT NULL DEFAULT 0.0,
    `walksPlusHits_total` INT NOT NULL DEFAULT 0,
    `strikeoutWalkRatio` DECIMAL(3,3) NOT NULL DEFAULT 0.0,
    `totalBasesAgainst` INT NOT NULL DEFAULT 0,
    `strikeouts_ratePerNineInnings` DECIMAL(3,3) NOT NULL DEFAULT 0.0,
    `strikeouts_total` INT NOT NULL DEFAULT 0,
    `stolenBasesAgainst_attempts` INT NOT NULL DEFAULT 0,
    `stolenBasesAgainst_caughtStealing` INT NOT NULL DEFAULT 0,
    `stolenBasesAgainst_total` INT NOT NULL DEFAULT 0,
    `saves_blown` INT NOT NULL DEFAULT 0,
    `saves_opportunities` INT NOT NULL DEFAULT 0,
    `saves_total` INT NOT NULL DEFAULT 0,
    `sacrifices_flies` INT NOT NULL DEFAULT 0,
    `sacrifices_hits` INT NOT NULL DEFAULT 0,
    `runSupport_ratePerNineInnings` DECIMAL(3,3) NOT NULL DEFAULT 0.0,
    `runSupport_total` INT NOT NULL DEFAULT 0,
    `runsAllowed_earnedRuns` INT NOT NULL DEFAULT 0,
    `runsAllowed_runsBattedIn` INT NOT NULL DEFAULT 0,
    `runsAllowed_total` INT NOT NULL DEFAULT 0,
    `pitches_pitchesPerInning` DECIMAL(3,3) NOT NULL DEFAULT 0.0,
    `pitches_total` INT NOT NULL DEFAULT 0,
    `holds` INT NOT NULL DEFAULT 0,
    `inheritedRunners_stranded` INT NOT NULL DEFAULT 0,
    `inheritedRunners_total` INT NOT NULL DEFAULT 0,
    `inningsPitched` DECIMAL(3,3) NOT NULL DEFAULT 0.0,
    `opponentAtBats` INT NOT NULL DEFAULT 0,
    `opponentBattingAverage` DECIMAL(3,3) NOT NULL DEFAULT 0.0,
    `opponentOnBasePercentage` DECIMAL(3,3) NOT NULL DEFAULT 0.0,
    `opponentSluggingPercentage` DECIMAL(3,3) NOT NULL DEFAULT 0.0,
    `pickoffs_pickoffsPlusPitcherCaughtStealing` INT NOT NULL DEFAULT 0,
    `pickoffs_throws` INT NOT NULL DEFAULT 0,
    `pickoffs_throwsPerBaserunner` DECIMAL(3,3) NOT NULL DEFAULT 0.0,
    `pickoffs_total` INT NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`));
